name: lamin
channels:
  - conda-forge
dependencies:
  - python=3.11
  - loguru
  - notebook
  - numpy
  - pandas
  - pip
  - polars
  - pyarrow
  - rich
  - s3fs
  - scanpy
  - zarr
  - tensorstore
  - pip:
      - bionty
      - lamindb==0.68
      - lnschema-bionty
      - rich-click
      - tiledbsoma==1.7.2
